GET http://localhost:3002/api/blogs HTTP/1.1
###
GET http://localhost:3002/api/blogs?search=post HTTP/1.1
###
POST http://localhost:3002/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVycm9ybGlrZUBleGFtcGxlLmNvbSIsImlkIjoxLCJpYXQiOjE3MjAyODYyMTZ9.9FeSdL4WbTkRLJ9hUdG-BCRXF6GKEhFAGD3avGqdz1o

{
    "author":"safsdfasd",
    "url":"http://localhost",
    "title":"dafsd post"
}
###
DELETE http://localhost:3002/api/blogs/13 HTTP/1.1

###
POST http://localhost:3002/api/blogs HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVycm9ybGlrZUBleGFtcGxlLmNvbSIsImlkIjoxLCJpYXQiOjE3MjAyODYyMTZ9.9FeSdL4WbTkRLJ9hUdG-BCRXF6GKEhFAGD3avGqdz1o
Content-Type: application/json

{
    "title":"ni post",
    "url":"url",
    "author":"errorlike",
    "likes":"42"
}
###
PUT http://localhost:3002/api/blogs/17 HTTP/1.1
Content-Type: application/json

{
    "likes":20
}
###
PUT http://localhost:3002/api/blogs/asdf HTTP/1.1
Content-Type: application/json

{
    "likes":20
}
###
DELETE http://localhost:3002/api/blogs/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVycm9ybGlrZUBleGFtcGxlLmNvbSIsImlkIjozLCJpYXQiOjE3MTk2MzM2MzV9.Eiy8OkkfRc5gSA9Ya9kIIK4lZac9QThDVfk4YaPRk10
###
GET http://localhost:3002/api/authors HTTP/1.1